### ISSUE TITLE
Proposal: merge all bloggy top links

### ISSUE THREAD

**Issue by treyhunner** [sandiegojs/sandiegojs.github.com#58]
I think the links for Archive, Categories, Pages, and Tags could all be put in a dropdown or they could be cross-linked to each other without being in the top bar (maybe a sub-menu?).

This would open up room for more links and remove the current clutter.

**Comment by kball** [comment]
+1 for cross linked without being in top bar.  I think pages is completely unnecessary and we could have categories, tags, and archive in a submenu e.g. on the blog post sidebar

**Comment by kball** [comment]
After mucking with this a little I think I might leave Archive in the top, as it doesn't make as much logical sense on a post page and I think still adds value.  I'll submit a PR for the other changes as suggested above
