### ISSUE TITLE
Add chat room page

### ISSUE THREAD

**Issue by treyhunner** [sandiegojs/sandiegojs.github.com#59]
Not all web programmers know how to use IRC.  Let's teach them so they can use our chat room!

Maybe add an explanation like this one? http://pythonsd.org/pages/chat-room.html

**Comment by kball** [comment]
Seams reasonable to me.  As a first pass, maybe we can just take that one and tweak it?  @treyhunner as our local representative of pythonsd do you feel ok with yanking wholesale?

**Comment by treyhunner** [comment]
@kball Sure let's just take it.  I wrote that page originally so I think it's fine.

**Comment by kball** [comment]
sounds good.  Ran out of time this morn but will do it later today
